name: Update me tonight

on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "Nothing here" > README.md #curl -O meme.html
      - uses: stefanzweifel/git-auto-commit-action@v4